finos/generator-symphony

generators/app/index.js, generators/java-bots/index.js, generators/java-bots/templates/java/bots/request-reply/pom.xml
Retrieve latest version number of java client library from maven central API to inject into pom.xml
=> Added dynamic versioning for java client library

generators/java-bots/templates/java/bots/expense-bot/src/main/java/ActionProcessor.java, generators/java-bots/templates/java/bots/expense-bot/src/main/java/ElementsListenerImpl.java, generators/java-bots/templates/java/bots/expense-bot/src/main/java/ExpenseBot.java, generators/java-bots/templates/java/bots/expense-bot/src/main/java/MessageSender.java, generators/node-bots/templates/node/bots/expense-bot/index.js
[PLS-345](https://perzoinc.atlassian.net/browse/PLS-345)
Updated NodeJs and Java version of ExpenseBot to send a IM/MIM message to referals after user submitted his expense form.
=> [PLS-345] ExpenseBot: Added approval request to referals

generators/app/index.js
Specify choices of languages for bot and application:
- Bot: Java, Nodejs, Python, .NET
- Application: Java, Nodejs
=> PLAT-9031 Specify choices of languages for bot and application

generators/python-bots/templates/python/bots/request-reply/listeners/elements_listener_impl.py, generators/python-bots/templates/python/bots/request-reply/listeners/im_listener_impl.py, generators/python-bots/templates/python/bots/request-reply/src/main.py
- Added await to async function on_im_message()
- Added Elements payload to logs
- Added elements listener to DF in main.py
=> APP-2874 Fix async bug

generators/java-bots/index.js
Error: 
```
$ yo symphony
/------------------------------------------/
/        SYMPHONY GENERATOR  1.2.3         /
/    by platformsolutions@symphony.com     /
/ (c) 2020 Symphony Communication Services /
/------------------------------------------/
? What do you want to create bot
? What is the name of your project x
? What is your POD subdomain
? What is your preferred programming language Java
? What is the BOT username megabot
? What is the BOT email address megabot@bot.symphony.com
? What is your preferred encryption technology RSA - Use Existing Keys
? Which template do you want to start with NLP Based Trade Workflow
* Generating bot Java code from NLP Based Trade Workflow template...
Looking for latest version of Camunda library..
Latest version of Camunda library is 1.0.3
Looking …
```
=> APP-3047 Fixed NLP Generator

package.json
[Ticket number](link to ticket)
=> [release] Bumped master to 1.5.0

README.md
Otherwise you don't have the yo command available
=> Add yo install step in README

generators/bdk/java/index.js
=> APP-3126 Fixed BDK version

package-lock.json, package.json
https://www.npmjs.com/package/generator-symphony/v/1.4.1
=> [release] Bumped 1.4-rc to 1.4.1

generators/bdk/java/index.js
[APP-3164](https://perzoinc.atlassian.net/browse/APP-3164)
Changed BDK_VERSION_DEFAULT to 1.4.0.BETA so that `yo symphony 2.0` uses latest BDK2.0 version.
=> APP-3164: Changed BDK_VERSION_DEFAULT to 1.4.0.BETA

generators/bdk/java/index.js, package.json
[APP-3164](https://perzoinc.atlassian.net/browse/APP-3164)
Release 1.4.2 to use latest BDK2.0 version which is 1.4.0.BETA
=> APP-3164: [release] Bumped 1.4-rc to 1.4.2

generators/bdk/java/templates/common/GifFormActivity.java.ejs, generators/bdk/java/templates/java/BotApplication.java.ejs, generators/bdk/java/templates/spring/GifSlashHandler.java.ejs, generators/bdk/java/templates/spring/OnUserJoinedRoomListener.java.ejs
[APP-3171](https://perzoinc.atlassian.net/browse/APP-3177)
Modified the java template files to accommodate with BDK 1.4.0.BETA changes.
=> APP-3171: updated the java template files for BDK 1.4.0.BETA

generators/bdk/java/templates/common/GifFormActivity.java.ejs, generators/bdk/java/templates/java/BotApplication.java.ejs, generators/bdk/java/templates/spring/GifSlashHandler.java.ejs, generators/bdk/java/templates/spring/OnUserJoinedRoomListener.java.ejs, package-lock.json, package.json
[APP-3177](https://perzoinc.atlassian.net/browse/APP-3177)
Release 1.4.3
=> 1.4.3 release

generators/bdk/index.js
[PLAT-10173](https://perzoinc.atlassian.net/browse/PLAT-10173)
Log a warning when folder to generate project is not empty. If the folder does not exist, the warning is not shown as the generator will create it (creates it beforehand).
=> PLAT-10173 : Warn developer if current folder is not empty

package.json
[PLAT-10544](https://perzoinc.atlassian.net/browse/PLAT-10544)
bumped version to 1.7.0 preparing for release
=> Prepare release : bump version to 1.7.0

generators/bdk/python/templates/ext-app/main.py.ejs
PLAT-10538
Updated in the extension app templates after missed modifications.
=> PLAT-10538: Updated python extension app

package.json
PLAT-10741
Bumped version to 1.7.1
=> Bumped version to 1.7.1

generators/bdk/python/index.js
PLAT-10794
Made Python generated project use BDK 2.0b2
=> PLAT-10794: Made Python generated project use BDK 2.0b2

generators/bdk/python/index.js, package.json
PLAT-10794
Prepare release 1.7.2
=> PLAT-10794: Release 1.7.2

README.md
PLAT-10830
Added a known issues part describing the issue and the workaround.
=> Updated readme following PLAT-10830

generators/bdk/python/index.js, generators/bdk/python/templates/bot-app/config.yaml.ejs, generators/bdk/python/templates/ext-app/config.yaml.ejs, test/python-bdk.spec.js
PLAT-10817
Added ssl truststore to python BDK projects
=> PLAT-10817: added ssl truststore to python BDK projects

generators/bdk/python/index.js, generators/bdk/python/templates/bot-app/activities.py.ejs, generators/bdk/python/templates/bot-app/gif.xml.ejs, generators/bdk/python/templates/bot-app/gif_activities.py.ejs, generators/bdk/python/templates/bot-app/main.py.ejs, generators/bdk/python/templates/requirements.txt.ejs, test/python-bdk.spec.js
PLAT-10873
PLAT-10828
Added examples of: slash command, CommandActivity, FormReplyActivity and UserJoinedRoomActivity
Added example of Jinja2 usage
=> PLAT-10873 PLAT-10828: Added more examples in the Python BDK bot

generators/bdk/python/templates/bot-app/gif_activities.py.ejs
PLAT-10828
Removed unused imports that I forgot in #118 
=> Removed unused imports in python BDK generated bot

README.md, generators/bdk/python/index.js, generators/bdk/python/templates/.gitignore.tpl, generators/bdk/python/templates/bot-app/__main__.py.ejs, generators/bdk/python/templates/bot-app/activities.py.ejs, generators/bdk/python/templates/bot-app/config.yaml.ejs, generators/bdk/python/templates/bot-app/gif.jinja2.ejs, generators/bdk/python/templates/bot-app/gif.xml.ejs, generators/bdk/python/templates/bot-app/gif_activities.py.ejs, generators/bdk/python/templates/bot-app/main.py.ejs, generators/bdk/python/templates/ext-app/__main__.py.ejs, generators/bdk/python/templates/ext-app/config.yaml.ejs, generators/bdk/python/templates/readme.md.ejs, generators/bdk/python/templates/requirements.txt.ejs, package.json, test/python-bdk.spec.js, yarn.lock
PLAT-10698
Release generator 1.7.3
=> PLAT-10698: Release 1.7.3

generators/bdk/python/templates/ext-app/__main__.py.ejs
PLAT-10698
Fixed path to static resources in the Python extension app
=> PLAT-10698: Fixed path to static folder for Python ext app

generators/bdk/python/index.js
PLAT-10943
Updated Python BDK version before releasing a new version
=> PLAT-10943: Updated Python BDK version

generators/bdk/python/index.js, package.json, yarn.lock
PLAT-10943
Release a new version 1.7.4
=> PLAT-10943: Release 1.7.4

generators/bdk/python/templates/ext-app/__main__.py.ejs, package.json
PLAT-10943
Forgot one commit in #125 
=> PLAT-10943: Release generator 1.7.5

generators/bdk/java/index.js, generators/bdk/java/templates/gradle/wrapper/gradle-wrapper.properties, generators/python-bots/templates/python/bots/elements_form/requirements.txt, generators/python-bots/templates/python/bots/request-reply/requirements.txt
[PLAT-11223](https://perzoinc.atlassian.net/browse/PLAT-11223)
Updated default java and python bdk versions after releasing Java BDK 2.2.1 and Python Legacy 1.3.6
=> PLAT-11223 updated default java and python bdk versions

generators/bdk/java/index.js, generators/bdk/java/templates/gradle/wrapper/gradle-wrapper.properties, generators/python-bots/templates/python/bots/elements_form/requirements.txt, generators/python-bots/templates/python/bots/request-reply/requirements.txt, package.json, yarn.lock
[PLAT-11223](https://perzoinc.atlassian.net/browse/PLAT-11223)
Backported:
- (#127)
- (#129)
Bumped the version to prepare release
=> PLAT-11223: release 1.7.6

generators/bdk/python/index.js, generators/bdk/python/templates/requirements.txt.ejs, test/python-bdk.spec.js
PLAT-11269
Updated requirements for python bdk projects, following the release of new python BDK version with new package name.
=> PLAT-11269: Updated requirements for python bdk projects

generators/bdk/python/index.js, generators/bdk/python/templates/requirements.txt.ejs, package.json, test/python-bdk.spec.js
https://perzoinc.atlassian.net/browse/PLAT-11269
Release 1.7.7
Contains #133
=> PLAT-11269: 1.7.7 release

generators/python/index.js
PLAT-11351
Updated Python BDK version after GA release
=> PLAT-11351: Updated Python BDK version after GA release

README.md, generators/java/index.js, package.json, yarn.lock
[PLAT-11325](https://perzoinc.atlassian.net/browse/PLAT-11325)
Updated readme to put that WDK is now supported.
Upgraded Java BDK version following the new release.
Bump generator version for a new release.
=> Updated readme with newly supported WDK

yarn.lock
[PLAT-11400](https://perzoinc.atlassian.net/browse/PLAT-11400)
In the previous commit #142 , yarn.lock file was mistakenly modified with downgraded versions. This commit sets it to the previous version from origin/master
=> Revert yarn.lock

CONTRIBUTING.md, README.md, generators/workflow/templates/README.md, generators/workflow/templates/application.yaml.ejs, generators/workflow/templates/build.gradle
Update Maven coordinates (group id changed)
Update URLs
Also drop an outdated section in CONTRIBUTING.md
=> WDK moved to Finos Github organization

package.json
[PLAT-11465](https://perzoinc.atlassian.net/browse/PLAT-11465)
Bumped version to 2.3.0 for a new release
=> Bump version to 2.3.0

README.md
[PLAT-11681](https://perzoinc.atlassian.net/browse/PLAT-11681)
Corrected this:
=> Update Readme.md: added a line break

.circleci/config.yml, package.json, yarn.lock
PLAT-11727
Forced colors dependency to 1.3.3 to avoid gibberish output
- [ x] Referenced a ticket in the PR title and in the corresponding section
=> Forced colors dependency to 1.3.3 to avoid gibberish output

package.json
PLAT-11727
Next release containing:
#163 
#164
=> Release 2.4.1

package.json
Preparing the first release of generator-symphony under finos scope.
=> Bump version to prepare new release

README.md
Since the package is now under Finos scope, we need to update the installation command in README.
=> Update README.md to use Finos scope in installation command

package.json
Bump version to 2.5.1 for new release
=> Bump version to 2.5.1 for new release

README.md
Update badges in README and Copyright
=> Update badges in README and Copyright

package.json
=> Bump version to release 2.5.2

package.json
Bumped the version to prepare the release 2.6.0
=> Bump version 2.6.0

package.json
Set Snapshot version after 2.6.0 release
=> Set Snapshot version

generators/python/templates/ext-app/__main__.py.ejs
Closes #202 
Add asyncio wrapper for aiohttp server to work correctly with Python BDK calls
=> Fix Python Ext App example with asyncio

generators/app/index.js, generators/java/index.js, generators/java/templates/ext-app/README.md
Closes #204
Added `README.md` for the Java Extension App project, detailing configuration options and how to get started using either a customer pod or the developer sandbox.
=> Added Java Ext App readme

generators/java/index.js, generators/python/index.js
=> Bump version to 2.6.1

generators/java/index.js
=> Update Java BDK default version to 2.14.0

generators/python/index.js
=> Update default version to 2.6.0

.github/workflows/build.yml, package.json, yarn.lock
=> Upgrade dependencies

package.json
=> Bump SNAPSHOT version

generators/workflow-docker/templates/startup.sh.ejs
=> Fix mount volume absolute path

generators/workflow-docker/index.js, generators/workflow-docker/templates/application.yaml.ejs, generators/workflow-docker/templates/startup.sh.ejs
Fix WDK Docker project:
- Relative volume not mounted correctly
- Missing passphrase config for secrets-enabled WDK
=> Fix WDK Docker mount and config

README.md
update from INCUBATING to ACTIVE
https://github.com/finos/finos-landscape/pull/200
=> FINOS stage ACTIVE
